{ lib }:
{
  username = "catitw";
  userfullname = "Xy Gu";
  useremail = "catitw@outlook.com";
  # generated by `mkpasswd -m scrypt --rounds=11`
  # https://man.archlinux.org/man/crypt.5.en
  initialHashedPassword = "$7$GU..../....MspJXZjuxqbMwHpPNbc5j/$vtn5GiscUsblDDo6bm.bJLyy4vw.Kl0OGl3CMXzW4lC";
}
